//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Группы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Группы()
        {
            this.Студенты_в_группах = new HashSet<Студенты_в_группах>();
        }
    
        public System.Guid ID_группы { get; set; }
        public System.Guid ID_Инженерной_школы { get; set; }
        public int Год_набора { get; set; }
        public int Длительность_обучения { get; set; }
        public int Код_формы_обучения { get; set; }
        public string Код_направления_подготовки { get; set; }
        public string Наименование { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студенты_в_группах> Студенты_в_группах { get; set; }
    }
}
